[package]
name = "smelt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cblas-sys = { version = "0.1.4", default-features = false }
half = {version = "2.2.1", features=["num-traits"], optional=true}
libc = { version = "0.2", default-features = false }
num-traits = { version = "0.2.15", optional=true}

[features]
intel-mkl = []
f16 = ["dep:half", "dep:num-traits"]
